# Generated by Django 4.1.3 on 2023-11-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
